project 'ReactNaitveTrackerTa.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ReactNaitveTrackerTa' do
rn_path = '../node_modules/react-native'
rn_maps_path = '../node_modules/react-native-maps'

pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'DevSupport',
]

pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"

pod 'RNI18n', :path => '../node_modules/react-native-i18n'
pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'
pod 'RNSVG', :path => '../node_modules/react-native-svg'
pod 'react-native-maps', path: rn_maps_path

end

# very important to have, unless you removed React dependencies for Libraries 
# and you rely on Cocoapods to manage it
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "React"
        target.remove_from_project
        end
    end
end
